cisco-open/camblet

internal/cli/cmd/agent/agent.go
=> rename the device

.github/settings.yml, CODEOWNERS
=> github: nasp-ify settings

.github/workflows/go.yml, config.yaml, internal/cli/cmd/agent/agent.go, pkg/agent/commands/csrsign.go, pkg/config/agent.go, pkg/config/config.go, pkg/rules/rule.go, pkg/tls/signer.go, rules.d/ci.yaml
=> support setting cert ttl

NOTICE, api/Makefile, api/agent/common/v1/common.proto, api/types/common.proto, pkg/agent/server/server.go, pkg/agent/server/util.go, pkg/plugin/workloadattestor/docker/cgroups.go, pkg/plugin/workloadattestor/docker/docker.go, pkg/plugin/workloadattestor/k8s/k8s.go, pkg/plugin/workloadattestor/k8s/kubelet_client.go, pkg/plugin/workloadattestor/k8s/util.go, pkg/plugin/workloadattestor/linux/util.go
This PR adds missing attribution to some inadvertently carried over code snippets from the Spire project.
=> Fix missing code affiliation

.goreleaser.yml, README.md, nasp.service
=> packages: add RPM format, add SD params to systemd service

.github/scripts/create_repos.sh, .github/workflows/site-deploy.yaml
=> Fix Release file since one should contain all

.github/scripts/create_repos.sh, .github/workflows/site-deploy.yaml
Add a proper Release description which claims that the repo is for nasp.
Propagate public key so it can be downloaded from the site itself.
=> Add proper Release description and propagate public key

nasp.d/rules/ci.yaml, pkg/rules/rule.go
change rule structure:
- move mTLS toggle from `properties` to `policy`
- add `passthrough` to `policy`
- change `spiffeID` to `allowedSPIFFEIDs` at `policy`
-
=> change rule structure

internal/cli/cmd/agent/agent.go
=> [cli] fix agent ca opts

.gitignore, .goreleaser.yml, deploy/debian-control
=> prepare release 0.3.0

.gitignore, Makefile, deploy/install.sh, deploy/rpmbuild/SPECS/nasp.spec, rpmbuild/SPECS/nasp.spec
This is the RPM version of the NASP meta package. Depends on https://github.com/cisco-open/nasp/pull/76
=> RPM meta package

site/docs/src/content/docs/start/installation.md
Add RPM related manual instructions as well.
=> extend install docs with RPM instructions

deploy/install.sh
Add the install script which contains the rpm repo requirements to site-v2 branch.
=> Add the enhanced install script to site-v2 branch

deploy/install.sh
=> fix install script on Amazon Linux

deploy/install.sh, site/docs/src/content/docs/start/installation.md
=> fix install script on Amazon Linux (#85)

deploy/install.sh
Otherwise installing users will get a lot of noise in dmesg.
=> installer: pass dynamic debug paramters to module

Makefile
=> add run target to makefile

.github/config/gh_projects.txt, README.md, deploy/debian-control, deploy/rpmbuild/SPECS/camblet.spec
=> prepare release 0.5.0

internal/policy/convert.go
=> fix policy id generation

.gitignore, Makefile, cmd/camblet/build.go, cmd/camblet/main.go, config.yaml, internal/cli/cli.go, internal/cli/cmd/agent/agent.go, internal/cli/cmd/root.go, pkg/config/agent.go, pkg/config/configuration.go
=> built time config dir support

site/docs/astro.config.mjs, site/docs/src/content/docs/talks.md
Add a new page about our past and future talks on the subject matter.
=> add talks page

site/docs/src/content/docs/concepts/service-registry.md
Adds a CLI example which generates a static registry file from Kubernetes. Thanks @waynz0r !
=> K8s registry example

site/docs/astro.config.mjs, site/docs/src/content/docs/start/installation.mdx, site/docs/src/content/docs/start/kubernetes.mdx, site/docs/src/content/docs/start/virtualmachine.mdx, site/docs/src/styles/custom.css
=> massaging vm quickstart

.github/workflows/release.yml, .goreleaser.yml, deploy/debian-control, deploy/rpmbuild/SPECS/camblet.spec
=> Prepare release 0.6.1

site/landing/yarn.lock
=> Yarn file fix

site/landing/pnpm-lock.yaml
=> Pnpm lock file fix

internal/service/convert.go
IPv4 mapped to IPv6 is not good enough for the kernel module.
=> fix ipv6 loopback resolving

deploy/debian-control, deploy/rpmbuild/SPECS/camblet.spec
=> Prepare release 0.7.0

deploy/debian-control, deploy/rpmbuild/SPECS/camblet.spec
=> Prepare release 0.7.1

camblet.d/policies/ci.yaml, camblet.d/services/ci.yaml
Example for https://github.com/cisco-open/camblet-driver/pull/213
=> add alpn=passthrough checker policy

camblet.d/policies/ci.yaml
This PR adds a new policy for the new flag test in the driver.
=> Add new policy for the flags test

.github/scripts/create_repos.sh
create_repos.sh did not handle errors from Github. Moreover, it did not fail in time which caused several issues during the release flow. This PR addresses this by failing fast in case of an error. It also prints the response from Git Hub, which makes debugging easier.
=> Fail fast and add more logs to create_repos.sh

Makefile, site/docs/src/content/docs/concepts/identity.md, site/docs/src/content/docs/concepts/kernel-module.md
Documenting the identity aspects of the wholebelevanc.
=> Document identity
